### ISSUE TITLE
[opensrv-mysql] Memory safety problem in `PacketReader`

### ISSUE THREAD

**Issue by tr5D5z9l** [datafuselabs/opensrv#49]
In mysql/src/packet_reader.rs, the following code has a memory safety problem:

```rust
let bytes = {
    // NOTE: this is all sorts of unfortunate. what we really want to do is to give
    // &self.bytes[self.start..] to `packet()`, and the lifetimes should all work
    // out. however, without NLL, borrowck doesn't realize that self.bytes is no
    // longer borrowed after the match, and so can be mutated.
    let bytes = &self.bytes[self.start..];
    unsafe { ::std::slice::from_raw_parts(bytes.as_ptr(), self.remaining) }
};
match packet(bytes) {
    Ok((rest, p)) => {
        self.remaining = rest.len();
        if self.remaining > 0 {
            self.bytes = rest.to_vec();
            self.start = 0;
        }
        return Ok(Some(p));
    }
    Err(nom::Err::Incomplete(_)) | Err(nom::Err::Error(_)) => {}
    Err(nom::Err::Failure(ctx)) => {
        self.bytes.truncate(self.remaining);
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("{:?}", ctx),
        ));
    }
}
```

We can see that `bytes` borrows `self.bytes`, then `p` in the `Ok` match arm also borrows `self.bytes` (the signature of `packet` function is `pub(crate) fn packet(i: &[u8]) -> nom::IResult<&[u8], (u8, Packet<'_>)>`. If `self.remaining > 0` holds, then the old `self.bytes` object will be dropped by `self.bytes = rest.to_vec();`, then `p` borrowing that object will be invalidated, but `p` will still be returned.

Another problem relating to pointer aliasing rule violation may exist: the statement `self.bytes.truncate(self.remaining);` creates a mutable borrow of `self.bytes`, while another immutable borrow of `self.bytes` is live (consider the variable `ctx`). By [language reference](https://doc.rust-lang.org/reference/behavior-considered-undefined.html), breaking the pointer aliasing rules will cause undefined behavior. This can be solved by rewriting the corresponding match arm to:

```rust
Err(nom::Err::Failure(ctx)) => {
    let err = Err(io::Error::new(
        io::ErrorKind::InvalidData,
        format!("{:?}", ctx),
    ));
    self.bytes.truncate(self.remaining);
    return err;
}
```

**Comment by drmingdrmer** [comment]
Thank you for your detailed report on the memory safety issue!
We'll reviews your findings!

**Comment by BohuTANG** [comment]
@tr5D5z9l 
Thank you for bringing up this matter and providing the solution.
We have fixed it based on your suggestion.
