### ISSUE TITLE
upgrade mysql_common

### ISSUE THREAD

**Issue by MichaelScofield** [datafuselabs/opensrv#53]
mysql_common has released new version 0.31.0, with the unsound dependency `lexical` removed, see here: https://github.com/blackbeam/rust_mysql_common/issues/102

Can opensrv-mysql upgrade its mysql_common dependency to 0.31.0?

**Comment by BohuTANG** [comment]
cc @PsiACE

**Comment by PsiACE** [comment]
Cool, let me give it a try.
