### ISSUE TITLE
valid data length for mysql timestamp binary encoding

### ISSUE THREAD

**Issue by MichaelScofield** [datafuselabs/opensrv#59]
In `decode.rs`:

https://github.com/datafuselabs/opensrv/blob/68aa6a05c7d31b292592d73fa87d994bdde36042/mysql/src/value/decode.rs#L236-L239

The code asserts that `v` must have length of either 7 or 11. 

However, it seems that 0 and 4 are also valid:

<img width="636" alt="image" src="https://github.com/datafuselabs/opensrv/assets/990479/80bad528-09f8-4b66-b17d-10f2469c69e7">

from https://mariadb.com/kb/en/resultset-row/#timestamp-binary-encoding

Any specific considerations why this assertion only makes 7 and 11 valid here?

**Comment by BohuTANG** [comment]
cc @PsiACE for a check.

**Comment by PsiACE** [comment]
The main reason is that, initially, only the encoding and decoding of data conforming to `chrono::NaiveDate` were considered. This was basically inherited from msql-srv. I think we need to carefully consider this case and point out why there are parts that are not fully compatible with the mysql protocol.

Later, I will conduct some tests to ensure that it does not disrupt existing behaviors.

Thank you very much for your Issue and PR.

**Comment by MichaelScofield** [comment]
ping @BohuTANG @PsiACE PTAL
