### ISSUE TITLE
Add tls support for opensrv-mysql

### ISSUE THREAD

**Issue by PsiACE** [datafuselabs/opensrv#6]
This will be available as an optional feature. We can track https://github.com/jonhoo/msql-srv/issues/23 for a reference implementation.

**Comment by Junnplus** [comment]
Since https://github.com/datafuselabs/opensrv/pull/12 , we can focus on async TLS support.

**Comment by SSebo** [comment]
@PsiACE @junnplus I would like to port https://github.com/jonhoo/msql-srv/issues/23 implementation to opensrv-mysql. Could you give me some advise?

**Comment by SSebo** [comment]
Just like https://github.com/jonhoo/msql-srv/pull/43 CI jonhoo/mysql-srv is broken as well.

**Comment by SSebo** [comment]
#34 @PsiACE This is a draft PR, lots of things to discuss. PTAL

**Comment by PsiACE** [comment]
>  The cert can be generated in time, or LICENSE checker can ignore cert file.

You can have the License check ignore the cert file if it will not expire.

**Comment by PsiACE** [comment]
thanks @SSebo , I just released v0.3.0 with tls support
